### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by GerardoNR** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-GerardoNR#1]
https://drive.google.com/file/d/1ybQ8-RximxJd7mmI-UHZL5AaKCQc6xm3/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
18 Puntos 

Mejorar detalles con información e imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
